version: "3.8"

networks:
    bibbox-default-network:
      external: true

services:
    §§INSTANCE-molgenis:
      image: registry.molgenis.org/molgenis/molgenis-app:8.4.2
      container_name: §§INSTANCE-molgenis
      networks:
        - bibbox-default-network
      environment:
        - molgenis.home=/home/molgenis
        - opencpu.uri.host=opencpu
        - elasticsearch.transport.addresses=elasticsearch:9300
        - db_uri=jdbc:postgresql://postgres/molgenis
        - db_user=molgenis
        - db_password=molgenis
        - admin.password=admin
        - MINIO_BUCKET_NAME=molgenis
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=molgenis
        - MINIO_SECRET_KEY=molgenis
        - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      ports:
        - "8097:8080"
      links:
        - §§INSTANCE-molgenis-postgres:postgres
        - §§INSTANCE-molgenis-minio:minio
        - §§INSTANCE-molgenis-elasticsearch:elasticsearch
        - §§INSTANCE-molgenis-opencpu:opencpu
      volumes: 
        - ./data/home/molgenis:/home/molgenis
        - ./data/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      depends_on:
        - §§INSTANCE-molgenis-postgres


    §§INSTANCE-molgenis-frontend:

      image: molgenis/molgenis-frontend:8.4.5
      container_name: §§INSTANCE-molgenis-frontend
      networks:
        - bibbox-default-network
      ports:
        - "80"
      volumes: 
        - ./data/backend.conf:/etc/nginx/proxy.d/backend.conf
      depends_on:
        - "§§INSTANCE-molgenis"
      links:
        - §§INSTANCE-molgenis:bibbox-molgenis

    §§INSTANCE-molgenis-postgres:
      image: postgres:11-alpine
      container_name: §§INSTANCE-molgenis-postgres
      networks:
        - bibbox-default-network
      environment:
        - POSTGRES_USER=molgenis
        - POSTGRES_PASSWORD=molgenis
        - POSTGRES_DB=molgenis
      expose:
        - "5432"
      volumes: 
        - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
      command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'

    §§INSTANCE-molgenis-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
      container_name: §§INSTANCE-molgenis-elasticsearch
      networks:
        - bibbox-default-network
      environment:
        - cluster.name=molgenis
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes: 
          - ./data/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200
        - 9300

    §§INSTANCE-molgenis-opencpu:
      image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
      container_name: §§INSTANCE-molgenis-opencpu
      networks:
        - bibbox-default-network
      ports:
        - 8004

    §§INSTANCE-molgenis-minio:
      image: minio/minio:RELEASE.2019-03-20T22-38-47Z
      container_name: §§INSTANCE-molgenis-minio
      networks:
        - bibbox-default-network
      volumes: 
        - ./data/minio/data:/data
      ports:
        - 9000
      environment:
        MINIO_ACCESS_KEY: molgenis
        MINIO_SECRET_KEY: molgenis
      command: server /data

    §§INSTANCE-molgenis-adminer:
      image: adminer
      container_name: §§INSTANCE-molgenis-adminer
      networks:
        - bibbox-default-network
      restart: unless-stopped
      links:
        - §§INSTANCE-molgenis-postgres:db
      ports:
        - 8080
      environment:
        - ADMINER_DEFAULT_SERVER=db
        - ADMINER_DEFAULT_USER=molgenis
        - ADMINER_DEFAULT_DATABASE=molgenis
        
